[package]
name = "rust-various"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "greeting"
path = "src/bin/greeting.rs"

[[bin]]
name = "wordcount"
path = "src/bin/wordcount.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
